microsoft/cordova-plugin-code-push

src/ios/CodePush.m
test/test.ts

Fixing a bug found by @lostintangent where on iOS 9 NSUserDefaults is immutable once created.
@dtivel @silhouettes @geof90

Fix for iOS 9 NSUserDefaults immutable change.

---

package.json
plugin.xml
samples/advanced/config.xml
samples/basic/config.xml
test/template/config.xml

I did not bump the dependency version of code-push, since in the latest release the [plugin.xml version was not increased](https://github.com/Microsoft/code-push/blob/master/sdk/plugin.xml#L2). This is okay for now since the acquisition code was not changed. We will bump all versions in the next release.
@lostintangent @geof90 @dtivel @silhouettes @nisheetjain

Bumped version to 1.1.0-beta.

---

plugin.xml

Adding a little more description to the plugin.xml file. I'm leaving the package.json description as-is, since on NPM, the entire readme is already displayed, and the current description helps make it clear that the module is a Cordova plugin.
For Cordova consumers (e.g. Visual Studio), the plugin is obviously for Cordova, so having the description provide a little context on what it is for, seems helpful. I'm using a variant of the slogan from the homepage, based on the recommendation from Amanda.

Changing plugin.xml description

---

README.md
test/projectManager.ts
test/test.ts

Changed tests and documentation to use prepare instead of build for updates. This simplifies update creation and significantly reduces test run time.
Thanks @lostintangent!
@dtivel @silhouettes @geof90 @nisheetjain

Prepare command for updates

---

README.md
www/codePush.ts

This simply changes two of the default dialog strings in order to match the existing behavior with the React Native plugin.

Changing default dialog strings

---

bin/www/codePush.js
bin/www/localPackage.js
bin/www/remotePackage.js
gulpfile.js
test/testUtil.ts
www/codePush.ts
www/localPackage.ts
www/remotePackage.ts

This PR updates some existing log messages to remove the use of the word "package" and be more consistent with the RN plugin logs. Additionally, I introduced new logs for the following scenarios:
1. Checking for an update, this way, a dev can see this is occurring, as opposed to needing to wait for the check to complete and display the up-to-date or update-available message
2. After an update is installed, we display a log indicating when it will be applied.
3. If an available update is being ignored due to having been blacklisted.
4. When displaying an update prompt, and if the user cancelled/ignored it.
5. If an available update is being ignored due to it targeting a newer binary version.
Additionally, this includes the JS files for #77, which I forgot to check-in.

Adding more logging

---

README.md

This PR primarily rewrites the `Releasing Updates` section to exclusively use the new `release-cordova` command in the CLI. It also adds a quick note about our confirmed support for CrossWalk.

Documenting release-cordova

---

bin/www/sdk.js
www/sdk.ts

Fixes https://github.com/Microsoft/cordova-plugin-code-push/issues/89. If a deployment key is not specified in the config.xml, we will still proceed if one was provided during the call to `checkForUpdate()`/`sync()`.

Fix deployment key override

---

src/ios/UpdateHashUtils.m

This PR simply fixes a build warning on iOS. It doesn't impact the app at all, but it may cause concern for users and it introduces unnecessary noise in the build output.

Fix build warning

---

package.json
src/android/CodePushReportingManager.java
src/ios/CodePushReportingManager.m
test/platform.ts

Fixes an issue with dependcy versions that could prevent an "npm install" from working correctly.
Fixes a reference case sensitivity issue in one of the test files.
Wraps reportStatus from native in a deviceready listener to prevent it from being called before codePush object is ready.
Should address issue https://github.com/Microsoft/cordova-plugin-code-push/issues/103
@lostintangent @dlebu @geof90

Fix timing issue with reporting status

---

src/android/CodePushReportingManager.java
src/ios/CodePushReportingManager.m

The crash itself was coming from attempting to save away some information in an NSDictionary with a nil value.
After some discussion, we decided that at this time, it would be best to no-op the reporting in the case where config.xml deployment key is not set, as this is consistent with the behaviour of the react native plugin, and it unblocks this scenario.
@lostintangent @dlebu @geof90

Work around crash with no deployment key in config.xml

---

test/test.ts

for some reason, the wkwebview tests are sending requests with X-CodePush-SDK-Version headers while the uiwebview tests do not, which the server was not configured to handle

fix WkWebView tests

---

package.json
test/template/www/js/scenarioRestart.js
test/test.ts

file transfer includes file@^3.0.0 as a dependency, but we install file@>=3.0.0. As a result, file transfer is incompatible with the version of file that we install and makes npm install exit with nonzero, even though it still installs everything and you can run everything fine. This fix keeps our dependency on file while allowing us to not have to update it to keep it consistent with the version that file-transfer depends on
Additionally, I removed the RESTART_SUCCEEDED message from the restartApplication test case. It was not being reliably sent on wkwebview (likely due to the webview being killed before it sends completely since it performs faster than uiwebview), and since when the restart step fails it will still call RESTART_FAILED and fail the test it's not necessary.
with this …

fix small bugs in testing

---

bin/www/codePush.js
bin/www/sdk.js
plugin.xml
src/android/CodePush.java
src/android/CodePushPreferences.java
src/android/CodePushReportingManager.java
src/android/ReportingStatus.java
src/android/StatusReport.java
src/ios/CodePush.m
src/ios/CodePushReportingManager.h
src/ios/CodePushReportingManager.m
src/ios/InstallOptions.h
src/ios/InstallOptions.m
src/ios/StatusReport.h
src/ios/StatusReport.m
typings/cordova.d.ts
www/codePush.ts
www/sdk.ts

This PR improves the reportStatus mechanism in order to make sure that metrics reporting calls are not lost due to bad network conditions, hence prevents metrics numbers from being "corrupted".
In a nutshell, if the call to the server fails/times out, we will save a copy of the statusReport in the Preferences, and retry again the next time the app resumes.

Retry reportStatus if failure

---

www/sdk.ts

I'm generating a config.xml in my project for each environment, and it turns out my config.xml generation script wasn't specifying the version correctly.
I wasted a lot of time today because of the vague error that was thrown when appVersion isn't found.
Hopefully this more specific error will save someone else some time.

getAcquisitionManager: specific error if no version in config.xml

---

src/ios/CodePush.h

The `updateSuccess` method was removed from the `CodePush` class in `v1.8.0`, and this PR simply removes it from the corresponding header file so that Xcode doesn't display a warning about it not being implemented.

Fixing header (iOS)

---

src/ios/CodePush.m

This addresses https://github.com/Microsoft/code-push/issues/256 by ensuring that expensive native operations are offloaded to a background thread. I modified the Cordova warning threshold to 1ms (instead of 10) for testing purposes, and moved all methods that took longer than that off of the UI thread. The biggest contributors were `getBinaryHash` and `notifyApplicationReady`, both of which were ~15ms+, which definitely shouldn't be done on the UI thread. The `preInstall` and `install` methods were steadily around 2ms as well, so I decided to offload them even though they aren't as impactful. All other methods were sub-millisecond, so I decided not to go crazy with this PR (even though our React Native plugin runs all native code on a background thread). We can always improve this later …

Backgrounding expensive operations (iOS)

---

src/ios/CodePush.m
src/ios/CodePushReportingManager.m

This fixes #137 by using the `WebViewEngine` to navigate the WebView instead of using the deprecated `loadRequest:` method on the UI/WKWebView class (which enforces new security rules in iOS 9.3+). The `webViewEngine` property was only added in Cordova iOS 4.0.0, and our plugin currently supports 3.9.0+, which is why I'm using `performSelector`/`id` type to actually perform the navigation. At some point, it might make sense for us to just start requiring 4.0.0+, at which point we can clean this code up. For now though, I don't want to change our platform compatibility.
Additionally, this fixes a regression I caused with #142. I had only tested that fix with `WKWebView` and it turns out that the `UIWebView` requires you to execute JS from the UI thread, so I need to ensure that we dispatch …

WKWebView fix

---

gulpfile.js
test/testUtil.ts

the parsing was including the device pairs as well as the regular devices, which would cause the booting of the simulator to fail and thus failing our automated tests occasionally.
the plugin testing framework has been updated with this change, but this is a hotfix until OSS approves it.

fix device list parsing issue

---

src/ios/CodePush.m

This PR fixes https://github.com/Microsoft/code-push/issues/268 by removing the runtime resolution of the `loadRequest:` selector, which can in some circumstances be ambitious due to their being multiple "versions" of this method available. Instead, we can perform the `WebViewEngine` vs. `WebView` check at compile-time, based on whether or not the host app is running Cordova iOS 4.0.0+, and then call the right `loadRequest:` method directly on each type, so that we don't need dynamic runtime resolution anyways.

Fixing PhoneGap Build issue

---

bin/www/sdk.js
gulpfile.js
package.json

The latest versions of our dev dependencies have some breaking changes, including requiring `typescript` to be installed in addition to the existing `gulp-typescript`, and an interface change in `tslint`.
This PR also updates the compiled js output, which was missing from a previous PR.

Tidy master

---

bin/www/httpRequester.js
samples/.gitignore
samples/advanced/config.xml
samples/basic/config.xml
www/httpRequester.ts

This is just a quick PR to send the plugin version as a header in requests to the CodePush server.
The acquisition SDK version currently being sent with requests is unreliable, because it is only updated rarely, and because it is shared with the React Native plugin.
Sending the actual `cordova-plugin-code-push` version allows the server to have fine-grained recognition of the exact plugin and version, and is necessary for breaking features such as the new CDN used to distribute updates.

Send plugin version with requests

---

package.json

Installation on VS fails because the `cordovaDependencies` resolution logic doesn't work with pre-release versions. Note that removing it will simply result in installation defaulting to the latest version. This should be acceptable, as it is highly unlikely at this point for a new user to be using a version of Cordova that we don't support, and even if they are, there is no version of our plugin that they would be able to use (and our docs do document this limitation clearly).

Remove cordovaDependencies - does not work with pre-release versions

---

README.md

Changed `codePush.sync(null, { updateDialog: { title: "An update is available!" } });`
to `codePush.sync(null, { updateDialog: { updateTitle: "An update is available!" } });`
due to there is no such property as `title` in `SyncOptions`.

readme: fixed “updateTitle” prop usage in example

---

src/android/CodePush.java

We should use `classes.dex` instead of `resources.arsc` to get correct build time for apk (https://github.com/Microsoft/cordova-plugin-code-push/issues/196)

Getting correct build time for apk

---

src/android/CodePush.java

This is for  'insurance'  that old packages will be cleared even if the timestamps are wrong because the app version is always bumped in production.

Added app version check for Android for consistency with iOS approach

---

bin/www/codePushUtil.js
bin/www/localPackage.js
bin/www/remotePackage.js
plugin.xml
test/test.ts

Relates to https://github.com/Microsoft/cordova-plugin-code-push/issues/243

Fix code-push version dependency, add support for latest typescript

---

bin/www/localPackage.js
plugin.xml
src/android/CodePush.java
src/android/UpdateHashUtils.java
src/ios/CodePush.h
src/ios/CodePush.m
src/ios/UpdateHashUtils.h
src/ios/UpdateHashUtils.m
www/localPackage.ts

This patch implements checking of the `packageHash` of downloaded updates for Android and iOS and implements code signing for iOS.

implement code signing for iOS, package hash checking for iOS and Android

---

plugin.xml
src/android/CodePush.java
src/android/CodePushException.java
src/android/build-extras.gradle

Code signing implemented for Android. As a reference implementation was taken the react native implementation. The requirement is to have public key in the `config.xml` with a key `CodePushPublicKey`. That same as the ios implementation of code signing.

Code signing implemented for Android

---

src/android/CodePush.java
src/android/UpdateHashUtils.java
src/android/Utilities.java

This PR is a proposal that fixes #303.
Since I couldn't find a easy and clean solution to determine if a the asset is a directory or not, I had a look how the `cordova-plugin-file` is solving this problem and according to the documentation recursion is not a good idea in the asset folder anyway: http://cordova.apache.org/docs/en/7.x/reference/cordova-plugin-file/index.html#slow-recursive-operations-for-android_asset.
My idea is to use the `cdvasset.manifest`, which we generate anyway during the build, to get a flat list containing the path to all the  asset within the `www` folder, which is later used for hash calculation.
The drawback is that we create a dependency to the `cdvCreateAssetManifest` build task, which should be clearly stated in case you accept my solution.

Fixed binary hash calculation on android.

---

bin/www/codePushUtil.js
www/codePushUtil.ts

This PR add stacktrace logging which is will be very handy to debug errors.

Add stacktrace logging

---

bin/www/codePushUtil.js
www/codePushUtil.ts

"Error in Error callbackId: TypeError: Cannot read property 'stack' of undefined"
The error (above) occurs when calling codePush.sync() when there are no existing downloaded updates. This patch fixes the bug.

Fix TypeError when calling logError without error.

---

hooks/beforeInstall.js

Added a fallback if installing zip plugin dependency for some reason fails. It attempts to install the stable version of zip plugin, used now. See [issue #354](https://github.com/Microsoft/cordova-plugin-code-push/issues/354).

Added fallback for zip plugin.

---

src/android/UpdateHashUtils.java

Fixes Android compilation failure:
```
:app:compileReleaseJavaWithJavac/Project/platforms/android/app/src/main/java/com/microsoft/cordova/UpdateHashUtils.java:63: error: cannot find symbol
} catch (FileNotFoundException e) {
^
symbol:   class FileNotFoundException
location: class UpdateHashUtils
```
/cc @iTOYS

Add missing FileNotFoundException import

---

hooks/afterPluginAdd.js

* Fixed ```execSync(cordovaCLI + ' plugin')```, because ```execSync('cordova plugin')``` couldn't work without global ```cordova``` installed
* Replaced ```deferral.reject``` with ```console.error``` to see the message in the console
* Added and tested **platform specific** cases
* Hide unnecessary output from ```execSync(cordovaCLI)``` commands

Fixed 'afterPluginAdd.js'

---

src/android/CodePush.java
src/ios/CodePush.m

- Check whether cordova-plugin-ionic-webview 2+ is installed on Android by looking for com.ionicframework.cordova.webview.IonicWebViewEngine class. If so, it calls IonicWebViewEngine.setServerBasePath instead of navigating to file via this.mainWebView.loadUrlIntoView(url, false);
- Check whether cordova-plugin-ionic-webview 2+ is installed on iOS by looking for setServerBasePath selector in webViewEngine. If so, splits NSUrl path components, removes last one, joins again and passes to webViewEngine as part of CDVInvokedUrlCommand.

Added cordova-plugin-ionic-webview 2+ support for Android and iOS

---

src/ios/CDVWKWebViewEngine+CodePush.m

**Issue:** Ionic app should call all file URL requests with `setServerBasePath` method otherwise app shows just white screen.
**Solution:** Replaced calling `setServerBasePath` method to using it with all URL request.
Related issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/486

Fix Ionic requests(white screen)

---

README.md

http://codepush.tools has expired, so I've update the URL to the migration page (https://microsoft.github.io/code-push/)

Update link to CodePush

---

src/android/CodePush.java

**Issue**: inside cordova config.xml if `<content src="index.html" />` is not index.html, after codepush update app will crash with StringIndexOutOfBoundsException
**Solution**: change hardcoded index.html to ConfigStartPageName

replace hardcoded index.html string with config defined content src

---

src/android/build-extras.gradle

Replacing deprecated leftShift operator with `doLast` for cdvCreateAssetManifest task in build-extras.gradle file
Related issue https://github.com/Microsoft/cordova-plugin-code-push/issues/512

Replace leftShift with 'doLast' for cdvCreateAssetManifest in build-extras.gradle file

---

package.json

This change will enable the use of the types of this package.
``` 
/// <reference types="cordova-plugin-code-push" />
```

Include "types" in the package.json

---

src/ios/CDVWKWebViewEngine+CodePush.m

**Issue**: WKWebView can't load codepush start page after terminating webView process.
**Error**: `Failed to load webpage with error: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)`
**Solution**: Override `didFailNavigation` method of CDVWKWebViewEngine in the `CDVWKWebViewEngine+CodePush.m` file. This method is executed after unsuccessful loading URL by WKWebView. In case if WebView was terminated and start page of viewController reference to codepush update then start page will be directly loaded repeatedly. Otherwise default implementation of `didFailNavigation` will be executed.
Related issue https://github.com/microsoft/cordova-plugin-code-push/issues/529

Fix webView inability to load codepush start page after terminating

---

README.md
bin/www/nativeAppInfo.js
package-lock.json
package.json
plugin.xml
samples/advanced/www/index.html
samples/basic/www/index.html
www/nativeAppInfo.ts

- Updating CodePush server host to `codepush.appcenter.ms`
- Updating the code-push sdk to version 3.0.0-beta.2
- Bump version number to 1.12.0-beta.0

Cutover to new code push SDK

---

src/android/build-extras.gradle

Fix bug on https://github.com/microsoft/cordova-plugin-code-push/issues/600

fix graddle conflict

---

src/android/CodePush.java
src/ios/CDVWKWebViewEngine+CodePush.m
src/ios/CodePush.m

Currently, the plugin does not contemplate opening other index.html within a cordova application, only the main index.html
An example would be to open another html index from a plugin in cordova.  (swift)
`     
let view = CDVViewController(nibName: nil, bundle: nil)
view.wwwFolderName = "file://www"
view.startPage = "mynewapp/index.html"
view.modalPresentationStyle = .fullScreen
let rootVIEW = UIApplication.shared.keyWindow?.rootViewController 
rootVIEW?.presentedViewController?.dismiss(animated: false, completion: nil)
rootVIEW?.present(view, animated: true, completion: nil)
`
So in that case your plugin will change the path to 
file://www/mynewapp/index.html and is NOT correct. because that file is not exist in that route. (plugin skip all the local server route, and for that is not …

fix(load): load different application path

---

README.md

CodePush SDK migrated to a new service. `Cordova-plugin-code-push` versions are lower than v1.12.0 will stop working in the near future

Add deprecating note

---

bin/www/localPackage.js
www/localPackage.ts

From https://github.com/microsoft/cordova-plugin-code-push/pull/631

Prevent error when publicKey or signature is an empty string

---

README.md

There were too many # so it wasn't rendering an h6

Fix H6 tag in readme

---

plugin.xml
src/ios/CDVViewController+CodePush.m
src/ios/CDVWKWebViewEngine+CodePush.m
src/ios/CodePush.m
src/ios/Utilities.h
src/ios/Utilities.m
src/ios/WebViewShared.h
src/ios/WebViewShared.m

Related issue #624.
This PR is similar to #635 but makes a fix more clear way.
Starting with cordova-ios 6 [`UIWebView` is replaced with `WKWebView` and also `WKURLSchemeHandler` is introduced](https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html). 
If add these parameters to `config.xml`
```xml
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
```
then `file://` requests are rejected by `WKURLSchemeHandler` which causes app to become blank after applying CodePush update.
There was already [a fix](https://github.com/microsoft/cordova-plugin-code-push/blob/master/src/ios/CDVWKWebViewEngine%2BCodePush.m#L56-L84) for that in `CDVWKWebViewEngine+CodePush.m` but it was applied only for the case when 
* cordova-ios 4, 5 was …

Fix cordova-ios 6 issue with file:// requests being rejected

---

README.md
src/ios/CodePush.m
src/ios/CodePushReportingManager.m
src/ios/Utilities.h
src/ios/Utilities.m

Related issue #624.
What this PR does:
* Starting with cordova-ios 6 [`UIWebView` is replaced with `WKWebView` and also `WKURLSchemeHandler` is introduced](https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html) which allow users to specify app scheme to avoid `file://` requests (that causes CORS issues). Previously Code Push update was loaded on WebView using `file://` requests, but now if app scheme is configured plugin will be using it to load the updated app page.
* Apple completely [drops support for UIWebView as of December 2020](https://developer.apple.com/news/?id=12232019b). PR removes support for UIWebView as well.

Fix cordova-ios v6 issues and remove UIWebView support
