microsoft/cordova-plugin-code-push

src/android/CodePush.java

The obvious way of fixing this issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/39

only call app start once

---

bin/www/codePush.js
bin/www/codePushUtil.js
bin/www/fileUtil.js
bin/www/httpRequester.js
bin/www/installMode.js
bin/www/localPackage.js
bin/www/nativeAppInfo.js
bin/www/package.js
bin/www/remotePackage.js
bin/www/sdk.js
gulpfile.js
src/ios/CodePush.m
src/ios/Reporting.h
src/ios/Reporting.m
test/test.ts
test/testUtil.ts

Update the plugin to be compatible with both UIWebView and WKWebView.
Addresses https://github.com/Microsoft/cordova-plugin-code-push/issues/60
@dlebu @lostintangent

Fix wkwebview compat

---

README.md
package.json
plugin.xml

This PR simply bumps the plugin version and adds mention to the README about the newly added support for WKWebView.

Version bump

---

test/test.ts
typings/codePush.d.ts
www/syncStatus.ts

when the sync was fixed I forgot to update the enum in the typings file

updated the codePush.d.ts typings file

---

bin/www/codePush.js
bin/www/localPackage.js
typings/codePush.d.ts
www/codePush.ts
www/localPackage.ts

https://github.com/Microsoft/cordova-plugin-code-push/issues/100

Fix mandatory install mode logging

---

.gitignore
CONTRIBUTING.md
gulpfile.js
package.json
test/test.ts

this is coupled with some changes on TFS that make the build output much friendlier

Added test reporter so that tests can report their success/failure rate

---

src/android/CodePush.java
src/ios/CodePush.m

This PR fixes an issue with reporting metrics in the case of a rollback.
Originally, `reportStatus` was called in the `handleUnconfirmedInstall` method, however, during that time the app startup process, the page and the `CodePush` javascript plugin has not been fully initialized, so executing the JS `codePush.reportStatus(...)` would just no-op.
This PR addresses that by caching the rollback status report in memory during `handleUnconfirmedInstall`, and only report the rollback when `notifyApplicationReady()` is called, at which point the app would be in the `deviceReady` state and all the plugins would have been fully initialized.

Fix rollback reporting

---

test/template/www/js/scenarioInstallOnRestart2xWithRevert.js
test/test.ts

i'm probably gonna have to make some more changes so that the tests are easier to understand (eventually) but this fixes Geoffrey's test case that was failing on Android only because the emulator is slower than the iOS emulator

fixed the test in #125

---

plugin.xml
src/ios/CDVWKWebViewEngine+CodePush.m

This is the final piece of the fix for #147.

WKWebView fix

---

.github/ISSUE_TEMPLATE.md

It reduces number of environment specific questions, so we could start investigation earlier

Add ISSUE_TEMPLATE.md file

---

package.json
plugin.xml

Bump version from 1.9.2-beta to 1.9.3-beta.

bump a new version since Nov 2016

---

.github/ISSUE_TEMPLATE.md
README.md

Due to multiple requests in discord chanel, https://github.com/Microsoft/react-native-code-push/issues/723, https://github.com/Microsoft/react-native-code-push/issues/717

Improved guide for creating different app keys more clear

---

www/localPackage.ts

See https://github.com/Microsoft/cordova-plugin-code-push/issues/250 for details

Fixed getPendingPackage do not return isMandatory prop

---

plugin.xml
www/localPackage.ts

Should fix Error when installing plugin in project with multiple platforms #258 and Update available #256 issues

Fix dependency issue

---

src/android/Utilities.java
src/android/build-extras.gradle

Fix incorrect long value restoration from strings.xml due to android sdk bug
#264

Fix incorrect long value restoration from strings.xml

---

www/codePush.ts

Was added only to js file initially

Added missing change to .ts file from #202

---

src/ios/CodePushReportingManager.m

Fix for issue https://github.com/Microsoft/cordova-plugin-code-push/issues/271

iOS11 WKWebView Crashfix

---

src/android/Utilities.java
src/android/build-extras.gradle

This PR updates assets manifest file location in `build-extras.gradle` due to since cordova-android v7 its was changed

[Android] Update assets manifest file location for build-extras.gradle

---

plugin.xml

Removed dependency that was causing the conflict during plugin installation (file dependency is already presented in file-transfer plugin).

Removed unnecessary dependency.

---

README.md

This PR adds note about how to release ionic apps.
Related to #344

Update docs with note about ionic apps specific

---

hooks/beforeInstall.js

It uses indexOf instead of includes due to issues with some clients. See #358

Added fix for post install script;

---

src/ios/CodePush.m

iOS:Execut all public methods in background thread

---

test/projectManager.ts
test/test.ts

Fixed 'gulp test-ios' command and couple tests

---

bin/www/localPackage.js
www/localPackage.ts

 Fix random updates failures

---

hooks/afterPluginAdd.js
plugin.xml

* Added `afterPluginInstall.js` with installation script for file, file-transfer, zip plugins.
* Removed these plugins from dependency.
Issue: #341

Install plugins throw AfterPluginAdd script

---

src/android/UpdateHashUtils.java

Ignoring missed files in binary assets folder

---

src/android/UpdateHashUtils.java

Ignore empty folders when computing assets hash

---

src/android/UpdateHashUtils.java

This commit added unneeded trailing whitespaces: 221faf9b623a592157e7d0065fe41234bb85de93

refactor(android): remove trailing whitespaces

---

package-lock.json
package.json
plugin.xml

* Ignore empty folders when computing assets hash
* Fixed issue with Ionic projects (liverelaod and loading local files)
* Code style

Release 1.11.10

---

hooks/afterPluginAdd.js

Updated hook to be backward compatible with older version of nodejs

Update file for backward compatibility

---

hooks/afterPluginAdd.js

* Prevent duplicated installing of dependency plugins.

Fix issue with installing dependency in case if add plugin just in config.xml

---

package-lock.json
package.json
plugin.xml

* Fix bug with installing dependent plugins.
* Added backward compatibility for older versions of NodeJS

Release 1.11.11

---

hooks/afterPluginAdd.js

* Created a function to check should we really install the plugin from hook or not, to prevent overriding plugin versions which are already specified in ```config.xml```

Fixes issue #425

---

package-lock.json
package.json
plugin.xml

Release  1.11.13

---

package-lock.json
package.json
plugin.xml

Release 1.11.14

---

package-lock.json
package.json

Bumped versions of `randomatic`, `deep-extend` and `replace`

Bumped dependency versions

---

src/android/CodePush.java

* Removed `catching Multiple Exception` (separated catches).
* Added `final` for `invoke` operation.
Related PR: https://github.com/Microsoft/cordova-plugin-code-push/pull/454
Related issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/470

Fixed compatibility issue for cordova-android@6.3.0 and less

---

package-lock.json
package.json
plugin.xml

Release 1.11.15

---

src/ios/CDVWKWebViewEngine+CodePush.m
src/ios/CodePush.h
src/ios/CodePush.m

Added check of change server path in case if this isn't CodePush path.
We should use this checking for preventing loading binary bundle after installing CodePush bundle.

Fix Ionic4

---

bin/www/fileUtil.js
www/fileUtil.ts

Fixed typescript compile issue. 
https://www.w3.org/TR/file-upload/#file-error-read

Fix compile issue

---

www/remotePackage.ts

**Issue**: Remote execution vulnerability
**Solution**: Remove argument for the flag (default false) for trust all hosts

Remove arg for download method

---

SUPPORT.md

This document aims to clarify support process and expectations for users of the project and contributors to the repo (in addition to `CONTRIBUTING.md`).

Add support process documentation

---

README.md

**Issue**: Using outdated command with CodePush CLI
**Solution**: Replace command with CodePush CLI to AppCenter CLI

Replace code-push CLI commands

---

plugin.xml

Bump version code

---

src/ios/CDVWKWebViewEngine+CodePush.m

**Issue**: Use of undeclared identifier **CDVUserAgentUtil**
**Solution**: Update logic for `didFailNavigation` method
**Related issue**: https://github.com/microsoft/cordova-plugin-code-push/issues/611

Update didFailNavigation method
